### ISSUE TITLE
URL dates not specified in drop menu are ignored

### ISSUE THREAD

**Issue by burnchar** [sujithravikumar/vacation-accrual-buddy#3]
https://vacationaccrual.azurewebsites.net/?StartDate=04%2F29%2F18 works (20180429), but https://vacationaccrual.azurewebsites.net/?StartDate=04%2F28%2F18 (20180428) is ignored; the date is reset to default.

**Comment by sujithravikumar** [comment]
Start Date field is a dropdown, since 20180428 is not one among the existing dropdown items, the date is reset to default.

The dropdown items are pre-populated based on the documented definition:
Start Date (Unit: Date) - Start date (Sunday) of the current pay period (2 weeks interval)

Please let me know if you have further questions, or can I close this issue?
